### ISSUE TITLE
TWT doesn't show the price

### ISSUE THREAD

**Issue by caherrerapa** [yonilevy/crypto-currency-symbols#14]
The coin is available but it shows empty for USDT
![Item-0_and_Item-0_and_Item-0](https://user-images.githubusercontent.com/1084920/106240636-33665580-6237-11eb-9dbd-385c379edcf9.jpg)

**Comment by yonilevy** [comment]
This repo isn't about CoinTick.
(But check out [CoinTick FAQ](https://yoni.ninja/cointick/faq))
