### ISSUE TITLE
Cake price no visible

### ISSUE THREAD

**Issue by ralts00** [yonilevy/crypto-currency-symbols#16]
I can never see the price of the cake :(

<img width="83" alt="Captura de Pantalla 2021-02-09 a la(s) 2 00 28" src="https://user-images.githubusercontent.com/5034252/107333155-b169fe00-6a7a-11eb-9df8-ae088dc72dca.png">

**Comment by yonilevy** [comment]
This repo isn't about CoinTick.
(But check out [CoinTick FAQ](https://yoni.ninja/cointick/faq))
