### ISSUE TITLE
Any good resources on how to make a custom symbol?

### ISSUE THREAD

**Issue by pushkatel** [yonilevy/crypto-currency-symbols#29]
I'd love to try and learn how to make a few symbols, just can't find anything good online

**Comment by yonilevy** [comment]
In the CoinTick app? There's no way to do that. But feel free to suggest a symbol here (in a reply to this comment) and if it's good it'll get added to the app.

**Comment by pushkatel** [comment]
Not in the CoinTick app, but in general? How could I contribute by taking the [SVG](https://cryptologos.cc/) and converting it to some format that would work with CoinTick. 

I mainly wanted to add symbols for CRO, DOT, MATIC and revise the Ethereum  symbol to the diamond one. These are the ones I use haha so I'm def have something spend my time on haha but could help with others

**Comment by yonilevy** [comment]
Oh, the goal of this repository (which should have been named "crypto-unicode-symbols") is to find unicode characters to represent crypto tokens. No images. You could [hunt for unicode characters](https://codepoints.net/planes.) similar to the symbol you have in mind.

**Comment by L422Y** [comment]
i second this, it would not be difficult to automate a build process for a custom font that could be included in the app, and it would make things much more user friendly, being able to use custom logos or symbols specific to projects instead of only pre-existing unicode characters

**Comment by yonilevy** [comment]
That's actually a pretty cool idea, so long as we stick to svg paths and try to come up with the simplest representation possible. I see there are existing collections like [this one](http://cryptoicons.co), but the icons are way too complex. If we're gonna do this I'd like to see the graphical representations that would make sense as unicode glyphs :)
