### ISSUE TITLE
App is Out of Date

### ISSUE THREAD

**Issue by FlorianWendelborn** [yonilevy/crypto-currency-symbols#30]
Sorry for pushing this, I’m sure you’re aware to some degree that it’s the case. But the remaining space in my menu bar is unfortunately getting very very tiny, so it’d be great if you could update the `crypto-currency-symbols` currently used in the app.

Right now, `MIOTA` and `NANO` take up a significant part of my menu bar:
![image](https://user-images.githubusercontent.com/1133858/159760306-b728839d-c30e-4b20-b43f-11c00cd4370c.png)

**Comment by yonilevy** [comment]
Thanks for writing!

If you're using the latest version of the app, give this a try: Options > Ticker > Symbol Display > Abbreviated.
It should turn "MIOTA" into "M" and "NANO" into "N".

On top of that, if you have unicode symbols to suggest for these coins, feel free to do so here :)

**Comment by FlorianWendelborn** [comment]
Ah, here’s why that suggestion didn’t work for me:
![image](https://user-images.githubusercontent.com/1133858/160302292-d778cd38-c3a3-48bc-9706-25da9a7b44e5.png)

I’m still on Big Sur since upgrading a hackintosh isn’t that easy unfortunately. Guess this is somewhat solved then.

If there’s no technical reasons why Monterey is actually required, I guess you could re-build for Big Sur in the future. But I’m fine with at some point being forced to upgrade.

**Comment by yonilevy** [comment]
Yeah, I rewrote the app at some point (Objective-C -> SwiftUI/Combine) and it was hard to avoid the new apis :(
