### ISSUE TITLE
Alternative Algorand symbol I created

### ISSUE THREAD

**Issue by ChrisOhgeNW** [yonilevy/crypto-currency-symbols#31]
⃫ ⃥ 
Created using 
[Space](http://www.unicode-symbol.com/u/0020.html)
+
[combining long double solidus overlay](http://www.unicode-symbol.com/u/20EB.html)
+
[Space](http://www.unicode-symbol.com/u/0020.html)
+
[combining reverse solidus overlay](http://www.unicode-symbol.com/u/20E5.html)
 +
 [Space](http://www.unicode-symbol.com/u/0020.html)

**Comment by yonilevy** [comment]
looks good, but seems to break surrounding text and doesn't render as expected in different environments, can't do

**Comment by yonilevy** [comment]
looks good, but seems to break surrounding text and doesn't render as expected in different environments, can't do
